# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [19]:
import numpy as np
arr=np.arange(10)
arr=arr.reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [50]:
a=np.arange(20).reshape(4,5)
a[2:4]=1
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [153]:
a=np.arange(20).reshape(2,10)
a[0][5:10]=1
a[1][5:10]=1
a[1][0]=5
a[1][1]=6
a[1][2]=7
a[1][3]=8
a[1][4]=9
a

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [166]:
arr=np.arange(80).reshape(10,8)
arr
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [200]:
arr=np.arange(100).reshape(5,4,5)
print("Arrays ",arr)
print("Arrays in one Dimension ",arr.ravel())

Arrays  [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]

 [[60 61 62 63 64]
  [65 66 67 68 69]
  [70 71 72 73 74]
  [75 76 77 78 79]]

 [[80 81 82 83 84]
  [85 86 87 88 89]
  [90 91 92 93 94]
  [95 96 97 98 99]]]
Arrays in one Dimension  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [201]:
arr=np.arange(100).reshape(5,4,5)
arr

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79]],

       [[80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [243]:
arr=np.random.rand(5,5)*100
print(np.square(arr))

[[8004.08602957 3395.43941004 5805.76280366 2957.79567814  271.58142556]
 [4331.21709117 7223.52153394  184.97303674   61.20324567 7885.3733694 ]
 [ 567.2219447  4364.66831502 8708.95222675 4166.27843082 4157.94497515]
 [2002.74062431 8777.882872   1003.18436782 7253.89118095  218.16098872]
 [4150.95890757 1465.55593338 5770.40471042 1537.85674952 3368.23114968]]


## Question:8

### Create 5x6 an array and find the mean?

In [301]:
arr=np.random.randint(2,9,size=(6,6))
np.mean(arr)

4.805555555555555

## Question:9

### Find the standard deviation of the previous array in Q8?

In [298]:
arr=np.random.randint(2,9,size=(6,6))
np.std(arr)

1.861525658640723

## Question:10

### Find the median of the previous array in Q8?

In [297]:
arr=np.random.randint(2,9,size=(6,6))
np.median(arr)

5.0

## Question:11

### Find the transpose of the previous array in Q8?

In [305]:
arr=np.random.randint(2,9,size=(6,6))
print("Array ",arr)
print("Transpose ",arr.transpose())

Array  [[2 8 8 7 6 3]
 [4 2 7 2 2 4]
 [2 2 6 8 7 3]
 [4 3 2 2 3 2]
 [8 4 6 2 7 6]
 [6 8 3 5 3 7]]
Transpose  [[2 4 2 4 8 6]
 [8 2 2 3 4 8]
 [8 7 6 2 6 3]
 [7 2 8 2 2 5]
 [6 2 7 3 7 3]
 [3 4 3 2 6 7]]


## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [316]:
arr=np.random.randint(2,9,size=(6,6))
print(arr,np.trace(arr))

[[6 5 2 7 5 5]
 [3 3 8 4 6 2]
 [6 6 6 3 7 5]
 [5 7 5 5 8 2]
 [6 5 2 3 7 4]
 [4 6 4 2 8 6]] 33


## Question:13

### Find the determinant of the previous array in Q12?

In [323]:
arr=np.random.randint(2,9,size=(6,6))
print(np.linalg.det(arr))

4512.000000000003


## Question:14

### Find the 5th and 95th percentile of an array?

In [338]:
arr=np.arange(20)
print("5TH Percentile of Array :",np.percentile(arr,5))
print("95TH Percentile of Array :",np.percentile(arr,95))

5TH Percentile of Array : 0.9500000000000001
95TH Percentile of Array : 18.05


## Question:15

### How to find if a given array has any null values?

In [340]:
arr=np.identity(10)
arr[0,0]=None
print(np.isnan(arr))

[[ True False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]]
